# Generated by Django 6.0.7 on 2026-08-08 16:45

from django.db import migrations, models
from django.utils.text import slugify


def populate_shop_slugs(apps, schema_editor):
    Shop = apps.get_model('customer', 'Shop')
    for shop in Shop.objects.all():
        if not shop.slug:
            shop.slug = slugify(shop.name)
            shop.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_category_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=False),
        ),
        migrations.RunPython(populate_shop_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
