# Generated by Django 6.0.7 on 2026-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_masterorder_order_master_order_payment_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
