# Generated by Django 6.1 on 2026-08-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Help & Support', max_length=200)),
                ('short_description', models.CharField(blank=True, default='How can we help you?', max_length=300)),
                ('order_help', models.TextField(blank=True, help_text='Order related help information')),
                ('delivery_help', models.TextField(blank=True, help_text='Delivery related help information')),
                ('payment_help', models.TextField(blank=True, help_text='Payment related help information')),
                ('cancellation_help', models.TextField(blank=True, help_text='Cancellation and refund information')),
                ('faq', models.TextField(blank=True, help_text='Frequently asked questions')),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_hours', models.CharField(blank=True, default='9:00 AM - 9:00 PM', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help & Support',
                'verbose_name_plural': 'Help & Support',
            },
        ),
    ]
