# Generated by Django 6.1 on 2026-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_termsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=120, unique=True)),
                ('mapped_text', models.CharField(help_text='Example: chappal -> slipper sandal footwear', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Alias',
                'verbose_name_plural': 'Search Aliases',
                'ordering': ['keyword'],
            },
        ),
    ]
