# Generated by Django 6.1 on 2026-08-29 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_searchalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AMEXA Wallet',
                'verbose_name_plural': 'AMEXA Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('ORDER_REWARD', 'Order Reward'), ('REFERRAL', 'Referral Reward'), ('PROMOTION', 'Promotion'), ('REDEEM', 'Coins Redeemed'), ('REFUND', 'Coins Refunded'), ('ADMIN', 'Admin Adjustment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('coins', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='customer.masterorder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='customer_wa_wallet__601f53_idx'), models.Index(fields=['reason'], name='customer_wa_reason_3723e8_idx')],
            },
        ),
    ]
