# Generated by Django 6.1 on 2026-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_referral_wallettransaction_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterorder',
            name='coin_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='masterorder',
            name='coins_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('ORDER_REWARD', 'Order Reward'), ('REFERRAL', 'Referral Reward'), ('PROMOTION', 'Promotion'), ('REDEEM', 'Coins Redeemed'), ('REFUND', 'Coins Refunded'), ('REVERSAL', 'Reward Reversal'), ('EXPIRED', 'Coins Expired'), ('ADMIN', 'Admin Adjustment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
