# Generated by Django 6.1 on 2026-08-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_masterorder_coin_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
