# Generated by Django 6.1 on 2026-08-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_deliveryassignment_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('HELP', 'Help Request'), ('CLAIM', 'Claim / Issue')], default='HELP', max_length=10)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_support_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_support_requests', to='customer.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
