# Generated by Django 6.1 on 2026-08-31 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_deliverysupportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('incentive_type', models.CharField(choices=[('DAILY', 'Daily Target'), ('WEEKLY', 'Weekly Target'), ('PEAK_HOURS', 'Peak Hours'), ('STREAK', 'Target Streak'), ('FESTIVAL', 'Festival Bonus')], default='DAILY', max_length=20)),
                ('required_deliveries', models.PositiveIntegerField(default=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('peak_start_time', models.TimeField(blank=True, null=True)),
                ('peak_end_time', models.TimeField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, default='Only successfully delivered orders count towards this target.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_incentives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIncentiveProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('completed_deliveries', models.PositiveIntegerField(default=0)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CREDITED', 'Bonus Credited'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_incentive_progress', to=settings.AUTH_USER_MODEL)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='customer.deliveryincentive')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='private/delivery/profile/')),
                ('full_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('vehicle_type', models.CharField(blank=True, choices=[('BICYCLE', 'Bicycle'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('EV', 'Electric Vehicle'), ('OTHER', 'Other')], max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Verification Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR_FRONT', 'Aadhaar Front'), ('AADHAAR_BACK', 'Aadhaar Back'), ('PAN', 'PAN Card'), ('DRIVING_LICENCE', 'Driving Licence'), ('VEHICLE_RC', 'Vehicle RC'), ('SELFIE', 'Verification Selfie')], max_length=30)),
                ('document_file', models.FileField(upload_to='private/delivery/documents/')),
                ('document_number_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('document_number_last4', models.CharField(blank=True, editable=False, max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_delivery_documents', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer.deliverypartnerprofile')),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_number_hash', models.CharField(editable=False, max_length=64)),
                ('account_number_last4', models.CharField(editable=False, max_length=4)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='private/delivery/bank/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_delivery_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='customer.deliverypartnerprofile')),
            ],
            options={
                'verbose_name': 'Delivery Partner Bank Account',
                'verbose_name_plural': 'Delivery Partner Bank Accounts',
            },
        ),
        migrations.AddIndex(
            model_name='deliveryincentive',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='customer_de_is_acti_366f26_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryincentiveprogress',
            index=models.Index(fields=['delivery_partner', 'status'], name='customer_de_deliver_e27ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryincentiveprogress',
            index=models.Index(fields=['period_start', 'period_end'], name='customer_de_period__83ae51_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryincentiveprogress',
            constraint=models.UniqueConstraint(fields=('incentive', 'delivery_partner', 'period_start'), name='unique_delivery_incentive_period'),
        ),
        migrations.AddIndex(
            model_name='deliverypartnerprofile',
            index=models.Index(fields=['verification_status', 'created_at'], name='customer_de_verific_54b5f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverypartnerdocument',
            constraint=models.UniqueConstraint(fields=('profile', 'document_type'), name='unique_delivery_profile_document_type'),
        ),
    ]
