# Generated by Django 6.1 on 2026-08-31 09:52

import customer.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_deliveryincentive_deliveryincentiveprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartnerbankaccount',
            name='cancelled_cheque',
            field=models.FileField(blank=True, null=True, storage=customer.storage_backends.AuthenticatedDeliveryDocumentStorage(), upload_to='private/delivery/bank/'),
        ),
        migrations.AlterField(
            model_name='deliverypartnerdocument',
            name='document_file',
            field=models.FileField(storage=customer.storage_backends.AuthenticatedDeliveryDocumentStorage(), upload_to='private/delivery/documents/'),
        ),
    ]
