# Generated by Django 6.1 on 2026-09-01 05:41

import customer.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_deliverypartnerbankaccount_cancelled_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='auto_accept_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='shop',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='shop',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('GROCERY', 'Grocery / Kirana'), ('FRUITS_VEGETABLES', 'Fruits & Vegetables'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery'), ('RESTAURANT', 'Restaurant / Cloud Kitchen'), ('PHARMACY', 'Pharmacy'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('GENERAL', 'General Store'), ('OTHER', 'Other')], default='GROCERY', max_length=30),
        ),
        migrations.CreateModel(
            name='ShopkeeperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='shopkeeper/profile/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residential_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Verification Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shopkeeper_profiles', to=settings.AUTH_USER_MODEL)),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopkeeper_profile', to='customer.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR_FRONT', 'Aadhaar Front'), ('AADHAAR_BACK', 'Aadhaar Back'), ('PAN', 'PAN Card'), ('GST_CERTIFICATE', 'GST Certificate'), ('FSSAI_CERTIFICATE', 'FSSAI / Food Licence'), ('OWNER_SELFIE', 'Owner Live Selfie'), ('SHOP_FRONT', 'Shop Front Photo')], max_length=30)),
                ('document_file', models.FileField(storage=customer.storage_backends.AuthenticatedDeliveryDocumentStorage(), upload_to='private/shopkeeper/documents/')),
                ('document_number_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('document_number_last4', models.CharField(blank=True, editable=False, max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shopkeeper_documents', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer.shopkeeperprofile')),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_number_hash', models.CharField(editable=False, max_length=64)),
                ('account_number_last4', models.CharField(editable=False, max_length=4)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, storage=customer.storage_backends.AuthenticatedDeliveryDocumentStorage(), upload_to='private/shopkeeper/bank/')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shopkeeper_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='customer.shopkeeperprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='shopkeeperprofile',
            index=models.Index(fields=['verification_status', 'created_at'], name='customer_sh_verific_e1456d_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopkeeperdocument',
            constraint=models.UniqueConstraint(fields=('profile', 'document_type'), name='unique_shopkeeper_profile_document_type'),
        ),
    ]
