# Generated by Django 6.1 on 2026-09-01 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_shop_auto_accept_orders_shop_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadInventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('CUSTOMER_RETURN', 'Customer Return'), ('MISSING', 'Missing'), ('OTHER', 'Other')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DEPLETED', 'Depleted')], db_index=True, default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'barcode'), name='unique_barcode_per_product'),
        ),
        migrations.AddField(
            model_name='badinventoryrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_bad_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badinventoryrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bad_inventory_records', to='customer.product'),
        ),
        migrations.AddField(
            model_name='badinventoryrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_inventory_records', to='customer.shop'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='customer.product'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='customer.shop'),
        ),
        migrations.AddField(
            model_name='badinventoryrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_inventory_records', to='customer.inventorybatch'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['shop', 'status', 'expiry_date'], name='customer_in_shop_id_00c029_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['shop', 'product', 'status'], name='customer_in_shop_id_d87269_idx'),
        ),
        migrations.AddIndex(
            model_name='badinventoryrecord',
            index=models.Index(fields=['shop', 'reason', 'created_at'], name='customer_ba_shop_id_40e203_idx'),
        ),
    ]
