# Generated by Django 6.1 on 2026-09-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_badinventoryrecord_inventorybatch_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(default='1 unit', help_text='Examples: 500 g, 1 litre, Pack of 6', max_length=40),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOPKEEPER', 'Shopkeeper'), ('PICKER', 'Order Picker'), ('DELIVERY', 'Delivery Partner'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=15),
        ),
        migrations.CreateModel(
            name='OrderPickingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Picker'), ('ACCEPTED', 'Accepted by Picker'), ('PICKING', 'Picking Items'), ('PACKED', 'Packed / Rider Assigned'), ('HANDED_OVER', 'Handed to Rider'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picking_task', to='customer.order')),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_tasks', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_tasks', to='customer.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPickingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(default=1)),
                ('picked_quantity', models.PositiveIntegerField(default=0)),
                ('last_scanned_barcode', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picking_item', to='customer.orderitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_items', to='customer.orderpickingtask')),
            ],
            options={
                'ordering': ['order_item__created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickers', to='customer.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shop', 'user__name'],
            },
        ),
        migrations.AddIndex(
            model_name='orderpickingtask',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='customer_or_shop_id_96750f_idx'),
        ),
    ]
