# Generated by Django 6.1 on 2026-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='current_area',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in metres.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
