# Generated by Django 6.1 on 2026-09-05 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_deliverypartnerprofile_current_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Saved Location',
                'verbose_name_plural': 'Customer Saved Locations',
            },
        ),
    ]
