# Generated by Django 6.1 on 2026-09-10 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_customersavedlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopkeeperWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('hold_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lifetime_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money_wallet', to='customer.shop')),
            ],
            options={
                'verbose_name': 'Shopkeeper Money Wallet',
                'verbose_name_plural': 'Shopkeeper Money Wallets',
            },
        ),
        migrations.CreateModel(
            name='SettlementClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_method', models.CharField(choices=[('BANK', 'Bank Account'), ('UPI', 'UPI')], default='BANK', max_length=10)),
                ('payout_upi_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('utr_reference', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_settlement_claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlement_claims', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_claims', to='customer.shop')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_claims', to='customer.shopkeeperwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='customer_se_shop_id_a244ca_idx'), models.Index(fields=['status', '-created_at'], name='customer_se_status_599891_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('ORDER_EARNING', 'Order Earning'), ('SETTLEMENT_CLAIM', 'Settlement Claim'), ('SETTLEMENT_PAID', 'Settlement Paid'), ('REFUND', 'Refund Adjustment'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('HOLD', 'Amount Put On Hold'), ('RELEASE', 'Hold Released'), ('REVERSAL', 'Reversal'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_wallet_transactions', to='customer.order')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='customer.settlement')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer.shopkeeperwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='customer_sh_wallet__bd0040_idx'), models.Index(fields=['reason'], name='customer_sh_reason_818086_idx')],
            },
        ),
    ]
